ALTER TABLE institutions 
ADD COLUMN bank_config JSON DEFAULT NULL,
ADD COLUMN bank_code VARCHAR(10) DEFAULT NULL,
ADD COLUMN bank_agency VARCHAR(20) DEFAULT NULL,
ADD COLUMN bank_account VARCHAR(20) DEFAULT NULL,
ADD COLUMN bank_wallet VARCHAR(10) DEFAULT NULL,
ADD COLUMN bank_agreement VARCHAR(20) DEFAULT NULL,
ADD COLUMN bank_assignor_name VARCHAR(100) DEFAULT NULL,
ADD COLUMN bank_assignor_document VARCHAR(20) DEFAULT NULL,
ADD COLUMN bank_assignor_address TEXT DEFAULT NULL;
